# Base Config to run all examples

# logging
run_name: ""
mode: "offline"
verbose: 0
checking_mode: 0 # if 1 you have to allow each new episode to start if 0 it will run without stopping

device: "cpu"
episodes: 1000

defaults:
  - _self_
  - agent: sac
  - env: walker-v0