name: openaillm
preprompt_dir: llm_data/preprompts/walker_v0.txt
openai_key: /home/sebastian/Documents/openai_key.txt
model: "gpt-3.5-turbo"
max_history_len: 15
# not used for random agent
batch_size: 256
num_updates: 2500
prefill_episodes: 0