name: sac
lr: 3e-4
batch_size: 256
num_updates: 1
prefill_episodes: 10

num_cells: 256
gamma: 0.99
soft_update_eps: 0.995
alpha_init: 1
fixed_alpha: False
loss_function: l2

normalization: None
dropout: 0.0

prb: 0
buffer_size: 1000000
pretrain: False

use_her_augmentation: True
her_generation_type: future
goal_thresholds: 20
samples: 4