name: sac
lr: 3e-4
batch_size: 256
num_updates: 20
prefill_episodes: 2

num_cells: 256
gamma: 0.99
soft_update_eps: 0.995
alpha_init: 1
fixed_alpha: False
loss_function: l2

normalization: LayerNorm
dropout: 0.01

prb: 0
buffer_size: 1000000
pretrain: False