name: td3
lr: 3e-4
batch_size: 256
num_updates: 1
prefill_episodes: 10

num_cells: 256
gamma: 0.99
soft_update_eps: 0.995
loss_function: smooth_l1
exploration_noise: 0.1 # 0.01

normalization: None
dropout: 0.0

prb: 0
buffer_size: 1000000
reset_params: False
use_bc: False
alpha: 1.0