name: CI

on:
# Runs on both push and pull_request events to the main branch.
  push:
    branches:
      - '**'  # or master, depending on your default branch
  pull_request:
    branches:
      - main  # or master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with pytest
      run: |
        pip install pytest
        pytest

    - name: Check code formatting with ufmt
      run: ufmt check .